apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-application-properties-configmap
  namespace: {{ .Values.namespace }}
data:
  application.properties: |-
{{ .Files.Get "config/application.properties" | nindent 4 }}
