
namespace: ecommerce

frontend:
  enabled: true
  replicaCount: 3
  image:
    repository: caramensuachua/ecommerce-frontend
    tag: fcaa81d
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: nginx
    host: ecommerce.devopsedu.vn
    port: 80
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi


backend:
  enabled: true
  replicaCount: 3
  image:
    repository: caramensuachua/ecommerce-backend
    tag: dc64736
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    className: nginx
    host: api-ecommerce.devopsedu.vn
    port: 8080
  secrets:
    MARIADB_DB: ZnVsbC1zdGFjay1lY29tbWVyY2U=
    MARIADB_HOST: ZGF0YWJhc2UtZGUxNTAuYzU0bWFpY3dvODhsLmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
    MARIADB_PASSWORD: TnRkMzQyMDAw
    MARIADB_PORT: MzMwNg==
    MARIADB_USERNAME: YWRtaW4=
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 350Mi

monitoring:
  storage:
    enabled: true
    className: nfs-storage
    pvName: monitoring-pv
    pvcName: monitoring-pvc
    capacity: 10Gi
    requestCapacity: 5Gi
    accessModes: ReadWriteOnce
    nfsPath: /data/monitoring
    nfsServer: "46.137.223.86"
  
  storage:
    className: nfs-storage
    capacity: 10Gi
    accessMode: ReadWriteOnce
    nfsServer: "46.137.223.86"
    # Danh sách các PV cần tạo
    volumes:
      - name: monitoring-pv-prometheus
        nfsPath: "/data/monitoring/prometheus"
      - name: monitoring-pv-grafana
        nfsPath: "/data/monitoring/grafana"

  
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.devopsedu.vn
    paths:
      - /


grafana:
  enabled: true
  persistence:
    enabled: true
    storageClassName: nfs-storage
    size: 10Gi
    type: pvc
  # Sửa lỗi Permission trên NFS
  initChownData:
    enabled: false
  podSecurityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.devopsedu.vn
    path: /
