
namespace: ecommerce

global:
  imagePullSecrets:
    - name: ecr-registry-helper
    
frontend:
  enabled: true
  replicaCount: 3
  image:
    repository: 573051981771.dkr.ecr.ap-southeast-1.amazonaws.com/de150/ecommerce-frontend
    tag: 86c5883
    pullPolicy: Always
  imagePullSecrets:
    - name: ecr-registry-helper
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: nginx
    host: ecommerce.devopsedu.vn
    port: 80
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi


backend:
  enabled: true
  replicaCount: 3
  image:
    repository: 573051981771.dkr.ecr.ap-southeast-1.amazonaws.com/de150/ecommerce-backend
    tag: a6de926
    pullPolicy: Always
  imagePullSecrets:
    - name: ecr-registry-helper
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    className: nginx
    host: api-ecommerce.devopsedu.vn
    port: 8080
  secrets:
    MARIADB_DB: ZnVsbC1zdGFjay1lY29tbWVyY2U=
    MARIADB_HOST: ZGF0YWJhc2UtZGUxNTAuYzU0bWFpY3dvODhsLmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
    MARIADB_PASSWORD: TnRkMzQyMDAw
    MARIADB_PORT: MzMwNg==
    MARIADB_USERNAME: YWRtaW4=
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 350Mi

monitoring:
  storage:
    enabled: true
    className: nfs-storage
    nfsServer: "46.137.223.86"
    capacity: 10Gi
    accessModes: ReadWriteOnce
    # Danh sách các bản ghi PV/PVC cần tạo
    volumes:
      - name: monitoring-pv-prometheus
        pvcName: monitoring-pvc-prometheus
        nfsPath: "/data/monitoring/prometheus"
      - name: monitoring-pv-grafana
        pvcName: monitoring-pvc-grafana
        nfsPath: "/data/monitoring/grafana"

  
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.devopsedu.vn
    paths:
      - /


grafana:
  enabled: true
  persistence:
    enabled: true
    storageClassName: nfs-storage
    size: 10Gi
    type: pvc
  # Sửa lỗi Permission trên NFS
  initChownData:
    enabled: false
  podSecurityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.devopsedu.vn
    path: /
