apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-frontend-autoscaling
  namespace: {{ .Values.namespace }}
spec:
  maxReplicas: {{ .Values.frontend.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.frontend.autoscaling.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-frontend-deployment
    targetCPUUtilizationPercentage: 50