apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MARIADB_DB: {{ .Values.backend.secrets.dbName }}
  MARIADB_HOST: {{ .Values.backend.secrets.dbHost }}
  MARIADB_PASSWORD: {{ .Values.backend.secrets.dbPassword }}
  MARIADB_PORT: {{ .Values.backend.secrets.dbPort }}
  MARIADB_USERNAME: {{ .Values.backend.secrets.dbUsername }}