apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MARIADB_DB: {{ .Values.backend.secrets.MARIADB_DB }}
  MARIADB_HOST: {{ .Values.backend.secrets.MARIADB_HOST }}
  MARIADB_PASSWORD: {{ .Values.backend.secrets.MARIADB_PASSWORD }}
  MARIADB_PORT: {{ .Values.backend.secrets.MARIADB_PORT }}
  MARIADB_USERNAME: {{ .Values.backend.secrets.MARIADB_USERNAME }}