apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-backend-application-properties-configmap
  namespace: ecommerce
data:
  # Sử dụng hàm nindent để đảm bảo thụt lề chuẩn cho khối String
  application-cam.properties: |-
    {{- with .Files.Get "config/application.properties" }}
    {{ . | nindent 4 }}
    {{- end }}
#.ss
