apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-backend
  name: {{ .Values.backend.name }}-backend-deployment
  namespace: ecommerce
spec:
  replicas: {{ .Values.backend.replicaCount}}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
      namespace: ecommerce
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: {{ .Release.Name }}-backend-application-properties-secret
                optional: false
          image: caramensuachua/ecommerce-backend:v2
          imagePullPolicy: Always
          name: {{ .Release.Name }}-backend
          ports:
            - containerPort: 8080
              name: tcp
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /run/src/main/resources/application.properties
              name: application-properties-config-volume
              subPath: application.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: ecommerce-backend-application-properties-configmap
          name: application-properties-config-volume