
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: {{ .Values.monitoring.storage.pvName }}
# spec:
#   capacity:
#     storage: {{ .Values.monitoring.storage.capacity }}
#   accessModes:
#     - {{ .Values.monitoring.storage.accessModes }}
#   nfs:
#     path: {{ .Values.monitoring.storage.nfsPath }}
#     server: {{ .Values.monitoring.storage.nfsServer }}
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: {{ .Values.monitoring.storage.className }}

{{- range .Values.monitoring.storage.volumes }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
spec:
  capacity:
    storage: {{ $.Values.monitoring.storage.capacity }}
  accessModes:
    - {{ $.Values.monitoring.storage.accessMode }}
  nfs:
    path: {{ .nfsPath }}
    server: {{ $.Values.monitoring.storage.nfsServer }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ $.Values.monitoring.storage.className }}
{{- end }}